/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package myproject;

import java.awt.*;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JButton;
import javax.swing.plaf.basic.BasicButtonUI;
import java.net.*;
import javax.swing.JLabel;
//import myproject.RSA_code;


/**
 *
 * @author santoosa
 */
public class GUIofEnDecTic extends javax.swing.JFrame {

    /**
     * Creates new form GUIofEnDecTic
     */
//    RSA_code r;
    CardLayout cr;
    String s,t,decipher;
    static Startframe g;
    JLabel w;

    
    
    public GUIofEnDecTic() {
        initComponents();
        
        Component [] cm=this.getContentPane().getComponents();
        for(Component cmo:cm){
            if(cmo instanceof JButton){
                ((JButton) cmo).setUI(new BasicButtonUI());
                ((JButton) cmo).setFocusPainted(false);
            }
        }
        cr=(CardLayout)Crdpane.getLayout();
       
        
//        s=EncryptPlainText
         if(g.send==true&&g.receive==false){
             try{
                 ServerSocket ser=new ServerSocket(1234);
                 Socket soc1=ser.accept();
                 if(soc1.isConnected())waitcon.setText("Connected with a client");
                 
                 
            
        }
        catch(Exception e){
            e.printStackTrace();
        }
            
             
           
        }
         else if(g.receive==true&&g.send==false){
             try{
                 InetAddress add=InetAddress.getLocalHost();
               Socket soc2=new Socket(add.getHostName(),1234);
               if(soc2.isConnected())waitcon.setText("Connected to server");
             }
             catch(Exception e){
                 e.printStackTrace();
             }
         }
         
         
         
         decipher=DecCipherText.getText();
       
        
    }
    public String gt(){
        return EncryptPlainText.getText();
    }
    static public void sete(String p){
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Crdpane = new javax.swing.JPanel();
        Keyexchangecard = new javax.swing.JPanel();
        Encryptcard = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        EncryptPlainText = new javax.swing.JTextArea();
        Encryptplainbutton = new javax.swing.JLabel();
        EncryptCipherbutton = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Encryptciphertext = new javax.swing.JTextArea();
        Sendencrypt = new javax.swing.JButton();
        waitcon = new javax.swing.JLabel();
        Decryptcard = new javax.swing.JPanel();
        DecPlain = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        DecCipherText = new javax.swing.JTextArea();
        DecCipher = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        DecPlainText = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EnDecTic");

        jPanel1.setBackground(new java.awt.Color(51, 0, 102));

        jButton2.setText("Encrypt Data");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Decrypt Data");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setText("Key Exchange");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(144, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        Crdpane.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout KeyexchangecardLayout = new javax.swing.GroupLayout(Keyexchangecard);
        Keyexchangecard.setLayout(KeyexchangecardLayout);
        KeyexchangecardLayout.setHorizontalGroup(
            KeyexchangecardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1124, Short.MAX_VALUE)
        );
        KeyexchangecardLayout.setVerticalGroup(
            KeyexchangecardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 533, Short.MAX_VALUE)
        );

        Crdpane.add(Keyexchangecard, "Keyexchangecard");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        EncryptPlainText.setBackground(new java.awt.Color(204, 255, 204));
        EncryptPlainText.setColumns(20);
        EncryptPlainText.setFont(new java.awt.Font("Waree", 2, 15)); // NOI18N
        EncryptPlainText.setLineWrap(true);
        EncryptPlainText.setRows(5);
        EncryptPlainText.setText("Hi, I am Santo");
        EncryptPlainText.setWrapStyleWord(true);
        jScrollPane1.setViewportView(EncryptPlainText);

        Encryptplainbutton.setFont(new java.awt.Font("Waree", 1, 15)); // NOI18N
        Encryptplainbutton.setText("Plain Text");
        Encryptplainbutton.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 51)));

        EncryptCipherbutton.setFont(new java.awt.Font("Waree", 1, 15)); // NOI18N
        EncryptCipherbutton.setText("Cipher Text");
        EncryptCipherbutton.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 51)));

        Encryptciphertext.setBackground(new java.awt.Color(255, 153, 153));
        Encryptciphertext.setColumns(20);
        Encryptciphertext.setFont(new java.awt.Font("Waree", 2, 15)); // NOI18N
        Encryptciphertext.setLineWrap(true);
        Encryptciphertext.setRows(5);
        jScrollPane2.setViewportView(Encryptciphertext);

        Sendencrypt.setText("Send");
        Sendencrypt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        Sendencrypt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendencryptActionPerformed(evt);
            }
        });

        waitcon.setBackground(new java.awt.Color(255, 255, 255));
        waitcon.setFont(new java.awt.Font("Liberation Sans", 3, 18)); // NOI18N
        waitcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        waitcon.setText("Waiting for Connection");
        waitcon.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 255), 10, true));

        javax.swing.GroupLayout EncryptcardLayout = new javax.swing.GroupLayout(Encryptcard);
        Encryptcard.setLayout(EncryptcardLayout);
        EncryptcardLayout.setHorizontalGroup(
            EncryptcardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EncryptcardLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(EncryptcardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Encryptplainbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(EncryptcardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EncryptcardLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(EncryptCipherbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EncryptcardLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Sendencrypt, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(EncryptcardLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 697, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(EncryptcardLayout.createSequentialGroup()
                .addGap(264, 264, 264)
                .addComponent(waitcon, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        EncryptcardLayout.setVerticalGroup(
            EncryptcardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EncryptcardLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(waitcon, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(EncryptcardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EncryptCipherbutton)
                    .addComponent(Encryptplainbutton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EncryptcardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EncryptcardLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(Sendencrypt)
                        .addGap(63, 63, 63))
                    .addGroup(EncryptcardLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(23, 23, 23))))
        );

        Crdpane.add(Encryptcard, "Encryptcard");

        DecPlain.setFont(new java.awt.Font("Waree", 1, 15)); // NOI18N
        DecPlain.setText("Plain Text");
        DecPlain.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 51)));

        DecCipherText.setColumns(20);
        DecCipherText.setLineWrap(true);
        DecCipherText.setRows(5);
        jScrollPane8.setViewportView(DecCipherText);

        DecCipher.setFont(new java.awt.Font("Waree", 1, 15)); // NOI18N
        DecCipher.setText("Cipher Text");
        DecCipher.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 51)));

        DecPlainText.setColumns(20);
        DecPlainText.setLineWrap(true);
        DecPlainText.setRows(5);
        jScrollPane9.setViewportView(DecPlainText);

        jButton4.setText("Decipher");
        jButton4.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("verify the message");
        jButton5.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout DecryptcardLayout = new javax.swing.GroupLayout(Decryptcard);
        Decryptcard.setLayout(DecryptcardLayout);
        DecryptcardLayout.setHorizontalGroup(
            DecryptcardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DecryptcardLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(DecryptcardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton5)
                    .addGroup(DecryptcardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(DecCipher, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(DecryptcardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DecryptcardLayout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addGroup(DecryptcardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DecPlain, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(206, Short.MAX_VALUE))
                    .addGroup(DecryptcardLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(215, 215, 215))))
        );
        DecryptcardLayout.setVerticalGroup(
            DecryptcardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DecryptcardLayout.createSequentialGroup()
                .addGroup(DecryptcardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DecryptcardLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(DecCipher))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DecryptcardLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(DecPlain)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DecryptcardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DecryptcardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addContainerGap(218, Short.MAX_VALUE))
        );

        Crdpane.add(Decryptcard, "Decryptcard");

        jSplitPane1.setRightComponent(Crdpane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        cr.show(Crdpane, "Encryptcard");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       cr.show(Crdpane, "Decryptcard");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void SendencryptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendencryptActionPerformed
      
        
       
      
    }//GEN-LAST:event_SendencryptActionPerformed

    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        DecPlainText.setText(decipher);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        cr.show(Crdpane, "Keyexchangecard");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIofEnDecTic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIofEnDecTic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIofEnDecTic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIofEnDecTic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new GUIofEnDecTic().setVisible(true);
        });
       
        
       
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Crdpane;
    private javax.swing.JLabel DecCipher;
    private javax.swing.JTextArea DecCipherText;
    private javax.swing.JLabel DecPlain;
    private javax.swing.JTextArea DecPlainText;
    private javax.swing.JPanel Decryptcard;
    private javax.swing.JLabel EncryptCipherbutton;
    private javax.swing.JTextArea EncryptPlainText;
    private javax.swing.JPanel Encryptcard;
    private javax.swing.JTextArea Encryptciphertext;
    private javax.swing.JLabel Encryptplainbutton;
    private javax.swing.JPanel Keyexchangecard;
    private javax.swing.JButton Sendencrypt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel waitcon;
    // End of variables declaration//GEN-END:variables
}
