/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package myproject;

//import java.awt.*;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JButton;
import javax.swing.plaf.basic.BasicButtonUI;
//import myproject.RSA_code;


/**
 *
 * @author santoosa
 */
public class GUIofEnDecTicClient extends javax.swing.JFrame {

    /**
     * Creates new form GUIofEnDecTic
     */
//    RSA_code r;
    CardLayout cr;
//    String s,t,decipher;
    
    
    public GUIofEnDecTicClient() {
        initComponents();
        
        Component [] cm=this.getContentPane().getComponents();
        for(Component cmo:cm){
            if(cmo instanceof JButton){
                ((JButton) cmo).setUI(new BasicButtonUI());
                ((JButton) cmo).setFocusPainted(false);
            }
        }
        cr=(CardLayout)Crdpane.getLayout();
        
//        s=EncryptPlainText
        
         
         
         
//         decipher=DecCipherText.getText();
       
        
    }
//    public String gt(){
//        return EncryptPlainText.getText();
//    }
//    public void sete(String p){
//        Encryptciphertext.setText(p);
//    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
//        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Crdpane = new javax.swing.JPanel();
        Keyexchangecard = new javax.swing.JPanel();
//        Encryptcard = new javax.swing.JPanel();
//        jScrollPane1 = new javax.swing.JScrollPane();
//        EncryptPlainText = new javax.swing.JTextArea();
//        Encryptplainbutton = new javax.swing.JLabel();
//        EncryptCipherbutton = new javax.swing.JLabel();
//        jScrollPane2 = new javax.swing.JScrollPane();
//        Encryptciphertext = new javax.swing.JTextArea();
//        primep = new javax.swing.JButton();
//        primeq = new javax.swing.JButton();
//        n = new javax.swing.JButton();
//        jScrollPane3 = new javax.swing.JScrollPane();
//        primeptext = new javax.swing.JTextArea();
//        jScrollPane4 = new javax.swing.JScrollPane();
//        primeqtext = new javax.swing.JTextArea();
//        jScrollPane5 = new javax.swing.JScrollPane();
//        ntext = new javax.swing.JTextArea();
//        phi = new javax.swing.JButton();
//        jScrollPane6 = new javax.swing.JScrollPane();
//        phitext = new javax.swing.JTextArea();
//        e = new javax.swing.JButton();
//        jScrollPane7 = new javax.swing.JScrollPane();
//        etext = new javax.swing.JTextArea();
//        Sendencrypt = new javax.swing.JButton();
        Decryptcard = new javax.swing.JPanel();
        DecPlain = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        DecCipherText = new javax.swing.JTextArea();
        DecCipher = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        DecPlainText = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EnDecTic");

        jPanel1.setBackground(new java.awt.Color(51, 0, 102));

        jButton1.setText("Key Exchange");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

//        jButton2.setText("Encrypt Data");
//        jButton2.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jButton2ActionPerformed(evt);
//            }
//        });

        jButton3.setText("Decrypt Data");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(127, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        Crdpane.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout KeyexchangecardLayout = new javax.swing.GroupLayout(Keyexchangecard);
        Keyexchangecard.setLayout(KeyexchangecardLayout);
        KeyexchangecardLayout.setHorizontalGroup(
            KeyexchangecardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1124, Short.MAX_VALUE)
        );
        KeyexchangecardLayout.setVerticalGroup(
            KeyexchangecardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 533, Short.MAX_VALUE)
        );

        Crdpane.add(Keyexchangecard, "Keyexchangecard");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

//        EncryptPlainText.setBackground(new java.awt.Color(204, 255, 204));
//        EncryptPlainText.setColumns(20);
//        EncryptPlainText.setFont(new java.awt.Font("Waree", 2, 15)); // NOI18N
//        EncryptPlainText.setLineWrap(true);
//        EncryptPlainText.setRows(5);
//        EncryptPlainText.setText("Hi, I am Santo");
//        EncryptPlainText.setWrapStyleWord(true);
//        jScrollPane1.setViewportView(EncryptPlainText);
//
//        Encryptplainbutton.setFont(new java.awt.Font("Waree", 1, 15)); // NOI18N
//        Encryptplainbutton.setText("Plain Text");
//        Encryptplainbutton.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 51)));
//
//        EncryptCipherbutton.setFont(new java.awt.Font("Waree", 1, 15)); // NOI18N
//        EncryptCipherbutton.setText("Cipher Text");
//        EncryptCipherbutton.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 51)));
//
//        Encryptciphertext.setBackground(new java.awt.Color(255, 153, 153));
//        Encryptciphertext.setColumns(20);
//        Encryptciphertext.setFont(new java.awt.Font("Waree", 2, 15)); // NOI18N
//        Encryptciphertext.setLineWrap(true);
//        Encryptciphertext.setRows(5);
//        jScrollPane2.setViewportView(Encryptciphertext);
//
//        primep.setText("Generate p");
//        primep.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Prime p", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Liberation Sans", 0, 15), new java.awt.Color(51, 0, 153))); // NOI18N
//        primep.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                primepActionPerformed(evt);
//            }
//        });
//
//        primeq.setText("Generate q");
//        primeq.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Prime q", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Liberation Sans", 0, 15), new java.awt.Color(51, 0, 153))); // NOI18N
//        primeq.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                primeqActionPerformed(evt);
//            }
//        });
//
//        n.setText("Calculate n");
//        n.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "n=p*q", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Liberation Sans", 0, 15), new java.awt.Color(51, 0, 153))); // NOI18N
//        n.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                nActionPerformed(evt);
//            }
//        });
//
//        primeptext.setColumns(20);
//        primeptext.setLineWrap(true);
//        primeptext.setRows(5);
//        primeptext.setText("187");
//        jScrollPane3.setViewportView(primeptext);
//
//        primeqtext.setColumns(20);
//        primeqtext.setLineWrap(true);
//        primeqtext.setRows(5);
//        jScrollPane4.setViewportView(primeqtext);
//
//        ntext.setColumns(20);
//        ntext.setLineWrap(true);
//        ntext.setRows(5);
//        jScrollPane5.setViewportView(ntext);
//
//        phi.setText("Calculate phi");
//        phi.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "phi=(p-1)*(q-1)", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Liberation Sans", 0, 15), new java.awt.Color(51, 0, 153))); // NOI18N
//        phi.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                phiActionPerformed(evt);
//            }
//        });
//
//        phitext.setColumns(20);
//        phitext.setLineWrap(true);
//        phitext.setRows(5);
//        jScrollPane6.setViewportView(phitext);
//
//        e.setText("Generate E");
//        e.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Encryption key", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Liberation Sans", 0, 15), new java.awt.Color(51, 0, 153))); // NOI18N
//        e.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                eActionPerformed(evt);
//            }
//        });
//
//        etext.setColumns(20);
//        etext.setLineWrap(true);
//        etext.setRows(5);
//        jScrollPane7.setViewportView(etext);
//
//        Sendencrypt.setText("Send");
//        Sendencrypt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
//        Sendencrypt.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                SendencryptActionPerformed(evt);
//            }
//        });
//
//        javax.swing.GroupLayout EncryptcardLayout = new javax.swing.GroupLayout(Encryptcard);
//        Encryptcard.setLayout(EncryptcardLayout);
//        EncryptcardLayout.setHorizontalGroup(
//            EncryptcardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(EncryptcardLayout.createSequentialGroup()
//                .addGroup(EncryptcardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addGroup(EncryptcardLayout.createSequentialGroup()
//                        .addContainerGap()
//                        .addGroup(EncryptcardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
//                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, EncryptcardLayout.createSequentialGroup()
//                                .addComponent(n, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                            .addGroup(EncryptcardLayout.createSequentialGroup()
//                                .addGroup(EncryptcardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
//                                    .addGroup(EncryptcardLayout.createSequentialGroup()
//                                        .addComponent(primeq, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                    .addGroup(EncryptcardLayout.createSequentialGroup()
//                                        .addComponent(primep, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
//                                .addGap(24, 24, 24))))
//                    .addGroup(EncryptcardLayout.createSequentialGroup()
//                        .addGap(15, 15, 15)
//                        .addGroup(EncryptcardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
//                            .addComponent(Encryptplainbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
//                .addGroup(EncryptcardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addGroup(EncryptcardLayout.createSequentialGroup()
//                        .addGroup(EncryptcardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EncryptcardLayout.createSequentialGroup()
//                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                                .addComponent(jScrollPane2))
//                            .addGroup(EncryptcardLayout.createSequentialGroup()
//                                .addGroup(EncryptcardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                    .addGroup(EncryptcardLayout.createSequentialGroup()
//                                        .addComponent(phi, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                    .addGroup(EncryptcardLayout.createSequentialGroup()
//                                        .addComponent(e, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
//                                .addGap(0, 334, Short.MAX_VALUE)))
//                        .addContainerGap())
//                    .addGroup(EncryptcardLayout.createSequentialGroup()
//                        .addComponent(EncryptCipherbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                        .addComponent(Sendencrypt, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
//                        .addGap(29, 29, 29))))
//        );
//        EncryptcardLayout.setVerticalGroup(
//            EncryptcardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EncryptcardLayout.createSequentialGroup()
//                .addGroup(EncryptcardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
//                    .addGroup(EncryptcardLayout.createSequentialGroup()
//                        .addGap(17, 17, 17)
//                        .addComponent(Encryptplainbutton)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                        .addComponent(jScrollPane1))
//                    .addGroup(EncryptcardLayout.createSequentialGroup()
//                        .addGap(55, 55, 55)
//                        .addGroup(EncryptcardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                            .addComponent(phi)
//                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
//                        .addGroup(EncryptcardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                            .addComponent(e)
//                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
//                        .addGap(23, 23, 23)
//                        .addGroup(EncryptcardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                            .addComponent(EncryptCipherbutton)
//                            .addComponent(Sendencrypt))))
//                .addGroup(EncryptcardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addGroup(EncryptcardLayout.createSequentialGroup()
//                        .addGap(20, 20, 20)
//                        .addGroup(EncryptcardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                            .addComponent(primep)
//                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
//                        .addGap(18, 18, 18)
//                        .addGroup(EncryptcardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                            .addComponent(primeq)
//                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
//                        .addGap(18, 18, 18)
//                        .addGroup(EncryptcardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                            .addComponent(n)
//                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
//                    .addGroup(EncryptcardLayout.createSequentialGroup()
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
//                .addGap(17, 17, 17))
//        );
//
//        Crdpane.add(Encryptcard, "Encryptcard");

        DecPlain.setFont(new java.awt.Font("Waree", 1, 15)); // NOI18N
        DecPlain.setText("Plain Text");
        DecPlain.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 51)));

        DecCipherText.setColumns(20);
        DecCipherText.setLineWrap(true);
        DecCipherText.setRows(5);
        jScrollPane8.setViewportView(DecCipherText);

        DecCipher.setFont(new java.awt.Font("Waree", 1, 15)); // NOI18N
        DecCipher.setText("Cipher Text");
        DecCipher.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 51)));

        DecPlainText.setColumns(20);
        DecPlainText.setLineWrap(true);
        DecPlainText.setRows(5);
        jScrollPane9.setViewportView(DecPlainText);

        jButton4.setText("Decipher");
        jButton4.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DecryptcardLayout = new javax.swing.GroupLayout(Decryptcard);
        Decryptcard.setLayout(DecryptcardLayout);
        DecryptcardLayout.setHorizontalGroup(
            DecryptcardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DecryptcardLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(DecryptcardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DecCipher, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(149, 149, 149)
                .addGroup(DecryptcardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DecPlain, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(206, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DecryptcardLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(472, 472, 472))
        );
        DecryptcardLayout.setVerticalGroup(
            DecryptcardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DecryptcardLayout.createSequentialGroup()
                .addGroup(DecryptcardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DecryptcardLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(DecCipher))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DecryptcardLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(DecPlain)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(DecryptcardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(88, 88, 88)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(147, Short.MAX_VALUE))
        );

        Crdpane.add(Decryptcard, "Decryptcard");

        jSplitPane1.setRightComponent(Crdpane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
               cr.show(Crdpane, "Keyexchangecard");
               
             
               
               
    }                                        
//
//    private void primepActionPerformed(java.awt.event.ActionEvent evt) {                                       
//        // TODO add your handling code here:
//    }                                      
//
//    private void primeqActionPerformed(java.awt.event.ActionEvent evt) {                                       
//        // TODO add your handling code here:
//    }                                      
//
//    private void nActionPerformed(java.awt.event.ActionEvent evt) {                                  
//        // TODO add your handling code here:
//    }                                 
//
//    private void phiActionPerformed(java.awt.event.ActionEvent evt) {                                    
//        // TODO add your handling code here:
//    }                                   
//
//    private void eActionPerformed(java.awt.event.ActionEvent evt) {                                  
//        // TODO add your handling code here:
//    }                                 

//    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
//        cr.show(Crdpane, "Encryptcard");
//    }                                        

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
       cr.show(Crdpane, "Decryptcard");
    }                                        

//    private void SendencryptActionPerformed(java.awt.event.ActionEvent evt) {                                            
//      
//        
//       
//      
//    }                                           

    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
//        DecPlainText.setText(decipher);
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIofEnDecTic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIofEnDecTic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIofEnDecTic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIofEnDecTic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new GUIofEnDecTicClient().setVisible(true);
        });
    }
    
    
    

    // Variables declaration - do not modify                     
    private javax.swing.JPanel Crdpane;
    private javax.swing.JLabel DecCipher;
    private javax.swing.JTextArea DecCipherText;
    private javax.swing.JLabel DecPlain;
    private javax.swing.JTextArea DecPlainText;
    private javax.swing.JPanel Decryptcard;
//    private javax.swing.JLabel EncryptCipherbutton;
//    private javax.swing.JTextArea EncryptPlainText;
//    private javax.swing.JPanel Encryptcard;
//    private javax.swing.JTextArea Encryptciphertext;
//    private javax.swing.JLabel Encryptplainbutton;
    private javax.swing.JPanel Keyexchangecard;
//    private javax.swing.JButton Sendencrypt;
//    private javax.swing.JButton e;
//    private javax.swing.JTextArea etext;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
//    private javax.swing.JScrollPane jScrollPane2;
//    private javax.swing.JScrollPane jScrollPane3;
//    private javax.swing.JScrollPane jScrollPane4;
//    private javax.swing.JScrollPane jScrollPane5;
//    private javax.swing.JScrollPane jScrollPane6;
//    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSplitPane jSplitPane1;
//    private javax.swing.JButton n;
//    private javax.swing.JTextArea ntext;
//    private javax.swing.JButton phi;
//    private javax.swing.JTextArea phitext;
//    private javax.swing.JButton primep;
//    private javax.swing.JTextArea primeptext;
//    private javax.swing.JButton primeq;
//    private javax.swing.JTextArea primeqtext;
    // End of variables declaration                   
}
